import Head from "next/head";
import styles from "@styles/Home.module.scss";
import Header from "@components/Header";
import Footer from "@components/Footer";
import Container from "@components/Container";
import Products from "@data/products.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Order Online | For A Better Economy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header />
      <main>
        <Container>
          <h1>Online Order</h1>
          <h2>Available Cards</h2>
          <ul className={styles.products}>
            {Products.map((product) => (
              <li key={product.title}>
                <img src={product.image} alt={product.title} />
                <h3>{product.title}</h3>
                <p>${product.price}</p>
                <button>Add to Cart</button>
              </li>
            ))}
          </ul>
        </Container>
      </main>
      <Footer />
    </div>
  );
}
